apiVersion: v1
kind: Service
metadata:
   name: ca4-part2-db
spec:
   type: NodePort
   ports:
      - name: db-port-8082
        port: 8082
        targetPort: 8082
        nodePort: 30082
      - name: db-port-9092
        port: 9092
        targetPort: 9092
        nodePort: 30092
   selector:
      app: ca4-part2-db