version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2-data:/usr/src/data-backup
      - "C:/Users/Mariana/OneDrive - Instituto Superior de Engenharia do Porto/Documents/GitHub/DevOps-23-24-JPE-1231845/CA4/Part2/db:/h2-backup/"
    networks:
      default:
        ipv4_address: 192.168.33.11

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.33.10
    depends_on:
      - "db"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24

volumes:
  h2-data:
